# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 14:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.FloatField()),
                ('road_type', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=25)),
                ('section_na', models.CharField(max_length=25)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=32636)),
            ],
        ),
    ]
