# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_auto_20180907_1423'),
    ]

    operations = [
    ]
