# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 22:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_healthcentre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('dname2014', models.CharField(blank=True, max_length=80, null=True)),
                ('subregion', models.CharField(blank=True, max_length=80, null=True)),
                ('region', models.CharField(blank=True, max_length=80, null=True)),
                ('hh2014', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('hhsize2014', models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True)),
                ('males2014', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('female2014', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pop_2014', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pop_urban', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pop_rural', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pop2013', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pop2010', models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True)),
                ('hh2010', models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True)),
                ('pop2002', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('hh2002', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('f1991_2002', models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True)),
                ('f2002_2014', models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True)),
                ('f1969_2014', models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True)),
                ('totcon2011', models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True)),
                ('accs_ele_h', models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True)),
                ('status', models.CharField(blank=True, max_length=80, null=True)),
                ('globalid', models.CharField(blank=True, max_length=80, null=True)),
                ('creationda', models.DateField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=80, null=True)),
                ('editdate', models.DateField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=80, null=True)),
                ('rai', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('rai_urb', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('rai_ub_pop', models.DecimalField(blank=True, decimal_places=11, max_digits=13, null=True)),
                ('new_rai', models.DecimalField(blank=True, decimal_places=11, max_digits=13, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'managed': False,
                'db_table': 'districts',
            },
        ),
    ]
