from django.db import models
from django.contrib.gis.db import models as geomodels

# Create your models here.
class HealthCentre(models.Model):
    objectid = models.IntegerField()
    name = models.CharField(max_length=254)
    lat = models.FloatField()
    lon = models.FloatField()
    osm_id = models.FloatField()
    timestamp = models.CharField(max_length=20)
    district = models.CharField(max_length=50)
    county = models.CharField(max_length=50)
    subcounty = models.CharField(max_length=50)
    source = models.CharField(max_length=50)
    collection = models.CharField(max_length=50)
    collecti_1 = models.CharField(max_length=50)
    grade = models.CharField(max_length=50)
    ownership = models.CharField(max_length=50)
    grid_dista = models.CharField(max_length=50)
    hc_name = models.CharField(max_length=254)
    hc_type = models.CharField(max_length=254)
    status = models.CharField(max_length=254)
    x_raw = models.FloatField()
    y_raw = models.FloatField()
    dname_2006 = models.CharField(max_length=254)
    cname_2006 = models.CharField(max_length=254)
    sname_2006 = models.CharField(max_length=254)
    pname_2006 = models.CharField(max_length=254)
    dname_2010 = models.CharField(max_length=254)
    sname_2010 = models.CharField(max_length=254)
    subregion = models.CharField(max_length=254)
    country = models.CharField(max_length=254)
    x_utm = models.FloatField()
    y_utm200k = models.FloatField()
    geom = geomodels.MultiPointField(srid=4326)
